services:
  dokkan-assets:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./assets:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
