---
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf.d/:/etc/traefik/conf.d/:ro
      - ./data/certs/:/var/traefik/certs/:rw
    networks:
      - proxy
    restart: unless-stopped
networks:
  proxy:
    external: true
