version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ${CONFIG_ROOT}/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
